### ISSUE TITLE
Using MapView methods

### ISSUE THREAD

**Issue by jr360codelab** [sgny/reason-react-native-maps#5]
How do I use methods for MapView? Where do I take MapView element from? As far as I can see it's required by most of the methods but there is no way to get it via ref because there is no such property for MapView.

**Comment by sgny** [comment]
Sorry for the oversight. I hadn't decided whether I should only define the `element` type or include ` ReactNative.NativeElement` (which brings in `NativeMethods` as well), I must have simply lost track of it altogether.

I'll quickly test if any of the React Native methods are actually available and push a PR to fix.

**Comment by sgny** [comment]
I have merged a commit, which should resolve this issue. Among `ReactNative.NativeMethods` only `findNodeHandle` seems to be supported so I added a simpler version of `NativeElement`.  

On another note, welcome to Github!

**Comment by jr360codelab** [comment]
It's working now, thank you :)
